<?php
/**
 * @file
 * Code for the Farm Food Safety feature.
 */

include_once 'farm_food_safety.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_food_safety_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_training' => array(
        'label' => t('Training'),
        'label_plural' => t('Trainings'),
        'view' => 'farm_food_safety_training',
        'farm_asset' => 'none',
      ),
      'farm_worker_health' => array(
        'label' => t('Worker health log'),
        'label_plural' => t('Worker health logs'),
        'view' => 'farm_food_safety_worker_health',
        'farm_asset' => 'none',
        'areas' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_food_safety_farm_log_categories() {

  // Provide an "Food Safety" log category.
  return array('Food Safety');
}
